// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SystemConfigurator.Config.Database;

#nullable disable

namespace SystemConfigurator.Config.Database.Migrations.CMA
{
    [DbContext(typeof(SystemDbCMAContext))]
    partial class SystemDbCMAContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SystemConfigurator.Model.CMA.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("AccountNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("account_no");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<Guid>("BirthplaceDistrictId")
                        .HasColumnType("uuid")
                        .HasColumnName("birthplace_district_id");

                    b.Property<string>("ContactPhoneNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_phone_no");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DomicileAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("domicile_address");

                    b.Property<int?>("DomicileCityId")
                        .HasColumnType("integer")
                        .HasColumnName("domicile_city_id");

                    b.Property<int?>("DomicileDistrictId")
                        .HasColumnType("integer")
                        .HasColumnName("domicile_district_id");

                    b.Property<int?>("DomicileProvinceId")
                        .HasColumnType("integer")
                        .HasColumnName("domicile_province_id");

                    b.Property<int?>("DomicileVillageId")
                        .HasColumnType("integer")
                        .HasColumnName("domicile_village_id");

                    b.Property<string>("DomicileZipcodeId")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("domicile_zipcode_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("GenderId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender_id");

                    b.Property<string>("HomePhoneNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("home_phone_no");

                    b.Property<string>("IdCardPhoto")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("id_card_photo");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("id_number");

                    b.Property<string>("IdentityTypeId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("identity_type_id");

                    b.Property<bool>("KycStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("kyc_status");

                    b.Property<DateTime?>("KycValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kyc_validated_at");

                    b.Property<DateTime?>("KycValidatedBy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kyc_validated_by");

                    b.Property<string>("LegalAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_address");

                    b.Property<int>("LegalCityId")
                        .HasColumnType("integer")
                        .HasColumnName("legal_city_id");

                    b.Property<int>("LegalDistrictId")
                        .HasColumnType("integer")
                        .HasColumnName("legal_district_id");

                    b.Property<int>("LegalProvinceId")
                        .HasColumnType("integer")
                        .HasColumnName("legal_province_id");

                    b.Property<int>("LegalVillageId")
                        .HasColumnType("integer")
                        .HasColumnName("legal_village_id");

                    b.Property<string>("LegalZipcodeId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("legal_zipcode_id");

                    b.Property<string>("MaritalStatusId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("marital_status_id");

                    b.Property<string>("MobilePhoneNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mobile_phone_no");

                    b.Property<string>("MobilePhoneNo2")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mobile_phone_no_2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("NationalityId")
                        .HasColumnType("uuid")
                        .HasColumnName("nationality_id");

                    b.Property<string>("Photo")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("photo");

                    b.Property<string>("TitleId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("title_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("CustomerId");

                    b.HasIndex("AccountNo")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GenderId");

                    b.HasIndex("IdentityTypeId");

                    b.HasIndex("MaritalStatusId");

                    b.HasIndex("NationalityId");

                    b.HasIndex("TitleId");

                    b.ToTable("cma_tbl_customer");
                });

            modelBuilder.Entity("SystemConfigurator.Model.CMA.LOV.Gender", b =>
                {
                    b.Property<string>("GenderId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("GenderId");

                    b.ToTable("cma_tbl_lov_customer_gender");
                });

            modelBuilder.Entity("SystemConfigurator.Model.CMA.LOV.IdentityType", b =>
                {
                    b.Property<string>("IdentityTypeId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("identity_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdentityTypeId");

                    b.ToTable("cma_tbl_lov_customer_identity_type");
                });

            modelBuilder.Entity("SystemConfigurator.Model.CMA.LOV.MaritalStatus", b =>
                {
                    b.Property<string>("MaritalStatusId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("marital_status_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("MaritalStatusId");

                    b.ToTable("cma_tbl_lov_customer_marital_status");
                });

            modelBuilder.Entity("SystemConfigurator.Model.CMA.LOV.Nationality", b =>
                {
                    b.Property<Guid>("NationalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("nationality_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("NationalityName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nationality_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("NationalityId");

                    b.ToTable("cma_tbl_lov_nationality");
                });

            modelBuilder.Entity("SystemConfigurator.Model.CMA.LOV.Title", b =>
                {
                    b.Property<string>("TitleId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("title_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TitleId");

                    b.ToTable("cma_tbl_lov_customer_title");
                });

            modelBuilder.Entity("SystemConfigurator.Model.CMA.Customer", b =>
                {
                    b.HasOne("SystemConfigurator.Model.CMA.LOV.Gender", "Gender")
                        .WithMany("Customers")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemConfigurator.Model.CMA.LOV.IdentityType", "IdentityType")
                        .WithMany("Customers")
                        .HasForeignKey("IdentityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemConfigurator.Model.CMA.LOV.MaritalStatus", "MaritalStatus")
                        .WithMany("Customers")
                        .HasForeignKey("MaritalStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemConfigurator.Model.CMA.LOV.Nationality", "Nationality")
                        .WithMany("Customers")
                        .HasForeignKey("NationalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemConfigurator.Model.CMA.LOV.Title", "Title")
                        .WithMany("Customers")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("IdentityType");

                    b.Navigation("MaritalStatus");

                    b.Navigation("Nationality");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("SystemConfigurator.Model.CMA.LOV.Gender", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("SystemConfigurator.Model.CMA.LOV.IdentityType", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("SystemConfigurator.Model.CMA.LOV.MaritalStatus", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("SystemConfigurator.Model.CMA.LOV.Nationality", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("SystemConfigurator.Model.CMA.LOV.Title", b =>
                {
                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
